package com.sample
 
import com.sample.QhpDetermination.Applicant;
 
rule "EligibilityDetermination_1"
salience 10
  when
        m : Applicant(FPL > 400)
    then
        System.out.println( "Qualified Health Plan" );
end

rule "EligibilityDetermination_2"
salience 20
  when
        m : Applicant(FPL>138,FPL < 400)
    then
        System.out.println( "Advanced Premium Tax Credits" );
end

rule "EligibilityDetermination_3"
salience 20
  when
        m : Applicant(FPL < 139)
    then
        System.out.println( "Medicaid" );
end